# Generated by Django 2.0.2 on 2018-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20180203_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterlistmodel',
            name='year',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018)], default=2018),
        ),
    ]
