# Generated by Django 2.0.2 on 2018-02-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20180203_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('course_credit', models.IntegerField(default=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='semesterlistmodel',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='courselistmodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.SemesterListModel'),
        ),
    ]
