# Generated by Django 2.0.2 on 2018-02-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20180203_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfferModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='courselistmodel',
            name='semester',
        ),
        migrations.AlterField(
            model_name='semesterlistmodel',
            name='semester',
            field=models.CharField(help_text='help: L1T1', max_length=10),
        ),
        migrations.AddField(
            model_name='courseoffermodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='admin_panel.CourseListModel'),
        ),
        migrations.AddField(
            model_name='courseoffermodel',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='admin_panel.SemesterListModel'),
        ),
    ]
