# Generated by Django 2.0.2 on 2018-02-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20180206_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffermodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
