# Generated by Django 2.0.2 on 2018-02-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_courseoffermodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffermodel',
            name='enrolled_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
