# Generated by Django 2.0.2 on 2018-02-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
    ]
