# Generated by Django 2.0.2 on 2018-02-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_semesterlistmodel_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterlistmodel',
            name='season',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=6, null=True),
        ),
    ]
