# Generated by Django 2.0.2 on 2018-03-27 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180221_2019'),
        ('admin_panel', '0013_auto_20180220_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAdvisorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Advisor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student', unique=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
