# Generated by Django 2.0.2 on 2018-03-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_studentsadvisormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsadvisormodel',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentsadvisormodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
