# Generated by Django 2.0.2 on 2018-03-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20180327_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsadvisormodel',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='studentsadvisormodel',
            name='number_of_course_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsadvisormodel',
            name='total_credit_taken',
            field=models.IntegerField(default=0),
        ),
    ]
