# Generated by Django 2.0.2 on 2018-03-29 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_auto_20180329_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsadvisormodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
