# Generated by Django 2.0.2 on 2018-03-31 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_auto_20180329_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsadvisormodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Student'),
        ),
    ]
