# Generated by Django 2.0.2 on 2018-02-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
